import { spawnSync } from "node:child_process";
import { cpSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

const root = fileURLToPath(new URL("../", import.meta.url));
const temporary: string[] = [];
afterEach(() => { for (const dir of temporary.splice(0)) rmSync(dir, { recursive: true, force: true }); });
const fixture = () => {
  const dir = mkdtempSync(join(tmpdir(), "fovea-proofs-"));
  temporary.push(dir);
  for (const path of ["LAWS.bend", "PROOF.bend", "proofs", "scripts/check-proofs.mjs", "scripts/compile-bend.mjs", "src/verified", "src/core/disclosure.ts"]) {
    cpSync(join(root, path), join(dir, path), { recursive: true });
  }
  symlinkSync(join(root, "node_modules"), join(dir, "node_modules"), "dir");
  return dir;
};
const gate = (cwd: string, ...args: string[]) => spawnSync(process.execPath, ["scripts/check-proofs.mjs", ...args], {
  cwd, encoding: "utf8", timeout: 60_000,
});

describe("Bend proof boundary", () => {
  it("checks without rewriting and rejects stale artifacts until explicit regeneration", () => {
    const dir = fixture();
    const path = join(dir, "src/verified/generated/kernel.js");
    const original = readFileSync(path, "utf8");
    expect(gate(dir).status).toBe(0);
    expect(readFileSync(path, "utf8")).toBe(original);
    writeFileSync(path, original.replace("Generated by Bend", "TAMPERED"));
    const stale = gate(dir);
    expect(stale.status).toBe(1);
    expect(stale.stderr).toContain("artifact is stale");
    expect(readFileSync(path, "utf8")).not.toBe(original);
    expect(gate(dir, "--write").status).toBe(0);
    expect(readFileSync(path, "utf8")).toBe(original);
  });

  it("rejects a false law before generating a replacement artifact", () => {
    const dir = fixture();
    const path = join(dir, "proofs/disclosure.bend");
    const generated = join(dir, "src/verified/generated/kernel.js");
    const original = readFileSync(generated, "utf8");
    writeFileSync(path, readFileSync(path, "utf8").replace("      Drop{}", "      Reveal{}"));
    const result = gate(dir, "--write");
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("scope_wins");
    expect(readFileSync(generated, "utf8")).toBe(original);
  });

  it("rejects transport that drops a source's mass", () => {
    const dir = fixture();
    const path = join(dir, "proofs/heat.bend");
    writeFileSync(path, readFileSync(path, "utf8").replace(
      "add(scale(mass, weights), transport(tail))", "transport(tail)",
    ));
    const result = gate(dir);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("heat_transport_mass");
  });

  it("requires a real column-normalization witness", () => {
    const dir = fixture();
    const path = join(dir, "PROOF.bend");
    writeFileSync(path, readFileSync(path, "utf8") + `
# This column sums to 1, not the claimed denominator 2.
def invalid_column() -> {H.sum(H.transport([H.Source{2n, [1n]}])) == 4n : Nat}:
  Laws.heat_transport_mass([H.Source{2n, [1n]}], 1n, ({==}, Unit{}))
`);
    const result = gate(dir);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("invalid_column");
  });

  it.each(["PROOF.bend", "proofs/nat-proof.bend", "proofs/kernel.bend"])(
    "rejects unsafe definitions in %s without rewriting the artifact", path => {
      const dir = fixture();
      const source = join(dir, path);
      const generated = join(dir, "src/verified/generated/kernel.js");
      const original = readFileSync(generated, "utf8");
      writeFileSync(source, readFileSync(source, "utf8") + "\n@unsafe def loop() -> Nat:\n  loop()\n");
      const result = gate(dir, "--write");
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("@unsafe is forbidden");
      expect(readFileSync(generated, "utf8")).toBe(original);
    },
  );

  it("follows newly introduced transitive imports when checking safety", () => {
    const dir = fixture();
    const source = join(dir, "proofs/nat-proof.bend");
    writeFileSync(source, readFileSync(source, "utf8") + "\nimport ./escape.bend as Escape\n");
    writeFileSync(join(dir, "proofs/escape.bend"), "import Base\n@unsafe def loop() -> Nat:\n  loop()\n");
    const result = gate(dir);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("escape.bend: @unsafe is forbidden");
  });

  it.each(["Array.fork", "Array.join"])("rejects the unsafe Base primitive %s", name => {
    const dir = fixture();
    const source = join(dir, "PROOF.bend");
    writeFileSync(source, readFileSync(source, "utf8") + `\ndef forbidden() -> Unit:\n  ${name}\n`);
    const result = gate(dir);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("unsafe Base primitive is forbidden");
  });

  it.each(['  import "./effect.js"', "import 0x1234/main.bend as Remote"])(
    "rejects unreviewed imports: %s", statement => {
      const dir = fixture();
      const source = join(dir, "PROOF.bend");
      writeFileSync(source, readFileSync(source, "utf8") + `\n${statement}\n`);
      const result = gate(dir);
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("only Base and local .bend imports are allowed");
    },
  );

  it("rejects imports escaping the repository lexically or through symlinks", () => {
    for (const indirect of [false, true]) {
      const dir = fixture();
      const source = join(dir, "PROOF.bend");
      if (indirect) symlinkSync(join(fixture(), "PROOF.bend"), join(dir, "outside.bend"));
      writeFileSync(source, readFileSync(source, "utf8")
        + `\nimport ${indirect ? "./outside.bend" : "../outside.bend"} as Outside\n`);
      const result = gate(dir);
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("imports must stay inside the repository");
    }
  });

  it("checks receipts without Bend and notices proof, ABI, adapter, or bridge drift", () => {
    const dir = fixture();
    const artifact = () => spawnSync(process.execPath, ["scripts/check-proofs.mjs", "--artifact"], {
      cwd: dir, encoding: "utf8", timeout: 60_000, env: { ...process.env, BEND: "./missing-bend" },
    });
    expect(artifact().status).toBe(0);
    for (const path of ["PROOF.bend", "proofs/kernel-abi.json", "scripts/compile-bend.mjs", "src/verified/policy.ts", "src/verified/generated/kernel.d.ts"]) {
      const file = join(dir, path);
      const original = readFileSync(file, "utf8");
      writeFileSync(file, original + "\n");
      const result = artifact();
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("artifact is stale");
      writeFileSync(file, original);
    }
  });

  it.each([
    ["D.disclosure(scope, excluded, seen, repeat, nucleus)", "D.disclosure(False{}, excluded, seen, repeat, nucleus)", "fresh_revealed"],
    ["C.fastShown(total, requested)", "total", "shown_bounded_by_total"],
    ["B.step(have, order)", "B.Done{}", "basis_empty_refused"],
  ])("the law covers the actual exported wrapper: %s", (before, after, law) => {
    const dir = fixture();
    const file = join(dir, "proofs/kernel.bend");
    writeFileSync(file, readFileSync(file, "utf8").replace(before, after));
    const result = gate(dir, "--write");
    expect(result.status).toBe(1);
    expect(result.stderr).toContain(law);
  });

  it("rejects a mismatched compiled ABI", () => {
    const dir = fixture();
    const path = join(dir, "proofs/kernel-abi.json");
    const abi = JSON.parse(readFileSync(path, "utf8"));
    abi.shownCount.splice(0, 0, ["extra", "bigint"]);
    writeFileSync(path, JSON.stringify(abi));
    const result = gate(dir, "--write");
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("Missing or incompatible compiled definition: shownCount");
  });

  it.each([
    ['text.replace("cli(process.argv.slice(2));", "cli([]);")', "Unrecognized Bend executable footer"],
    ['"console.log(process.pid);\\n" + text', "Effectful runtime escaped"],
  ])("rejects compiler bridge drift: %s", (mutate, message) => {
    const dir = fixture();
    const fake = join(dir, "fake-bend");
    writeFileSync(fake, `#!/usr/bin/env node
const {execFileSync} = require("node:child_process");
const fs = require("node:fs");
const args = process.argv.slice(2);
process.stdout.write(execFileSync(${JSON.stringify(process.env.BEND ?? "bend")}, args, {encoding:"utf8", maxBuffer:16777216}));
if (args.includes("-o")) {
  const path = args[args.indexOf("-o") + 1];
  const text = fs.readFileSync(path, "utf8");
  fs.writeFileSync(path, ${mutate});
}
`, { mode: 0o755 });
    const result = spawnSync(process.execPath, ["scripts/check-proofs.mjs", "--write"], {
      cwd: dir, encoding: "utf8", timeout: 60_000, env: { ...process.env, BEND: fake },
    });
    expect(result.status).toBe(1);
    expect(result.stderr).toContain(message);
  });

  it("ignores quoted/commented tokens and never executes a proof main", () => {
    const dir = fixture();
    const source = join(dir, "PROOF.bend");
    writeFileSync(source, readFileSync(source, "utf8") + `
# @unsafe Array.fork import ./not-real.bend
def note() -> String:
  "# @unsafe Array.join import ./not-real.bend"
def main() -> IO(Unit):
  IO.print("PROOF_MAIN_MUST_NOT_EXECUTE")
`);
    const result = gate(dir, "--write");
    expect(result.status).toBe(0);
    expect(result.stdout).not.toContain("PROOF_MAIN_MUST_NOT_EXECUTE");
  });

  it.each([
    ["@unsafe\ndef Added.escape() -> Nat:\n  0n", "unsafe declarations changed"],
    ["def indirect() -> Unit:\n  Array.fork", "Base references Array.fork"],
  ])("rejects drift in the pinned Base safety boundary: %s", (extra, message) => {
    const dir = fixture();
    const fake = join(dir, "fake-bend");
    const base = "@unsafe\ndef Array.fork() -> Unit:\n  Unit{}\n@unsafe\ndef Array.join() -> Unit:\n  Unit{}\n" + extra;
    writeFileSync(fake, `#!/usr/bin/env node
if (process.argv[2] === "version") console.log("bend 2.0.26");
else if (process.argv[2] === "base") console.log(${JSON.stringify(base)});
else process.exit(99);
`, { mode: 0o755 });
    const result = spawnSync(process.execPath, ["scripts/check-proofs.mjs"], {
      cwd: dir, encoding: "utf8", timeout: 60_000, env: { ...process.env, BEND: fake },
    });
    expect(result.status).toBe(1);
    expect(result.stderr).toContain(message);
  });

  it("rejects an unproved law", () => {
    const dir = fixture();
    const path = join(dir, "PROOF.bend");
    writeFileSync(path, readFileSync(path, "utf8").replace(
      "def Laws.scope_wins(excluded, seen, repeat, nucleus):\n  {==}\n", "",
    ));
    const result = gate(dir);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("not a valid proof yet");
  });
});
