// Library extraction follows Pi Fabric's pinned Bend bridge. No algorithm is
// translated: expose compiler-produced definitions through its own trampoline.
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { build, transform, version as esbuild } from "esbuild";
import ts from "typescript";

export const toolchain = { esbuild, typescript: ts.version };

export async function compileKernel(root, bend) {
  const temp = mkdtempSync(join(tmpdir(), "fovea-bend-"));
  try {
    const emitted = join(temp, "kernel.js");
    bend(["proofs/kernel.bend", "-o", emitted]);
    const js = readFileSync(emitted, "utf8");
    const ast = ts.createSourceFile("kernel.js", js, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
    if (ast.parseDiagnostics.length) throw new Error("Invalid JavaScript emitted by Bend");
    const statements = [...ast.statements];
    const footer = statements.slice(-2).map(statement => statement.getText(ast).replace(/\s/g, ""));
    if (footer[0] !== "cli(process.argv.slice(2));" || footer[1] !== "io_exit($main$,null);") {
      throw new Error("Unrecognized Bend executable footer; audit the bridge before upgrading");
    }
    const defs = new Map(statements.filter(ts.isFunctionDeclaration).map(node => [node.name?.text, node]));
    const abi = JSON.parse(readFileSync(join(root, "proofs/kernel-abi.json"), "utf8"));
    const exports = Object.entries(abi).map(([name, signature]) => {
      const symbol = `$${name}$`;
      const arity = signature.length - 1;
      if (!/^[A-Za-z][A-Za-z0-9]*$/.test(name) || arity < 0 || defs.get(symbol)?.parameters.length !== arity) {
        throw new Error(`Missing or incompatible compiled definition: ${name}`);
      }
      return `export const ${name} = /* @__PURE__ */ run_lib(${symbol}, ${arity});`;
    });
    const library = js.slice(0, statements.at(-2).getFullStart()) + "\n" + exports.join("\n");
    const bundled = await build({
      stdin: { contents: library, sourcefile: "bend-kernel.js", resolveDir: root },
      bundle: true, write: false, format: "esm", platform: "node", target: "es2022",
      packages: "external", external: ["bun:ffi"], treeShaking: true, minifySyntax: true, legalComments: "none",
    });
    const pure = bundled.outputFiles[0].text;
    const generated = ts.createSourceFile("pure.js", pure, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
    if (generated.statements.some(ts.isImportDeclaration) || /\b(?:process|globalThis|console|fetch|eval|Function|io_exit|io_push|require|__require)\b/.test(pure)) {
      throw new Error("Effectful runtime escaped into the generated kernel");
    }
    const code = (await transform(pure, {
      format: "esm", target: "es2022", minifyIdentifiers: true, minifySyntax: true, legalComments: "none",
      banner: "// Generated by Bend 2.0.26; do not edit. See LAWS.bend and PROOF.bend.\n"
        + "// Includes adapted Bend runtime/Base, Copyright 2026 HigherOrderCO, Apache-2.0.\n"
        + "// CLI removed and library exports added by Pi Fovea; see THIRD_PARTY_NOTICES.md.",
    })).code;
    const types = "// Generated ABI; see proofs/kernel-abi.json.\n"
      + readFileSync(join(root, "proofs/kernel-types.d.ts"), "utf8") + "\n"
      + Object.entries(abi).map(([name, signature]) => {
        const args = signature.slice(0, -1).map(([name, type]) => `${name}: ${type}`).join(", ");
        return `export declare function ${name}(${args}): ${signature.at(-1)};`;
      }).join("\n") + "\n";
    return { "src/verified/generated/kernel.js": code, "src/verified/generated/kernel.d.ts": types };
  } finally {
    rmSync(temp, { recursive: true, force: true });
  }
}
